databases:
  - name: test_resurrectism_postgres
    databaseName: resurrectism_production
    user: resurrectism
    region: frankfurt

services:
  - type: web
    name: test_resurrectism_api
    region: frankfurt
    env: ruby
    repo: https://github.com/resurrectism/api.git
    branch: main
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    domains:
      - test.api.resurrectism.space
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: test_resurrectism_postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false # placeholder for a value to be added in the dashboard

  - type: web
    env: static
    name: test_resurrectism_frontend
    buildCommand: "yarn build"
    staticPublishPath: "./dist"
    branch: main
    repo: https://github.com/resurrectism/frontend.git
    domains:
      - test.resurrectism.space
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
    envVars:
      - key: VITE_API_URL
        value: "https://test.api.resurrectism.space"
