databases:
  - name: resurrectism_postgres
    databaseName: resurrectism_production
    user: resurrectism
    region: frankfurt

services:
  - type: web
    env: ruby
    name: resurrectism_api
    region: frankfurt
    repo: https://github.com/resurrectism/api.git
    branch: production
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    healthCheckPath: /health_check
    domains:
      - api.resurrectism.space
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: resurrectism_postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

  - type: web
    env: static
    name: resurrectism_frontend
    buildCommand: "yarn build"
    staticPublishPath: "./dist"
    branch: production
    repo: https://github.com/resurrectism/frontend.git
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
    domains:
      - resurrectism.space
    envVars:
      - key: VITE_API_URL
        value: "https://api.resurrectism.space"
