databases:
  - name: resurrectism_production
    databaseName: resurrectism_production
    user: resurrectism

services:
  - type: web
    env: ruby
    name: resurrectism
    repo: https://github.com/resurrectism/api.git
    branch: main
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    domains:
      - api.resurrectism.space
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: resurrectism_production
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

  - type: web
    env: static
    name: resurrectism_frontend
    buildCommand: "yarn build"
    staticPublishPath: "./dist"
    branch: main
    repo: https://github.com/resurrectism/frontend.git
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
    domains:
      - resurrectism.space
    envVars:
      - key: VITE_API_URL
        value: "https://api.resurrectism.space"
